### ISSUE TITLE
Experience bar breaks css style

### ISSUE THREAD

**Issue by MrShellad** [FoskyM/flarum-custom-levels#1]
The experience bar breaks the css style of the page

**Comment by MrShellad** [comment]
.CustomLevel-level {
  float: left;
  position: relative;
  margin-left: -85px;
  margin-top: 75px;
  width: 64px;
  text-align: center;
}
The problem is margin-top

**Comment by FoskyM** [comment]
Thank you for feedback, however, it works well on my site. 
Please reply with screenshots of the problem or your site's url, so that I can solve it.
