### ISSUE TITLE
Issue when viewed on mobile

### ISSUE THREAD

**Issue by orschiro** [FoskyM/flarum-custom-levels#13]
The levels show up in the middle of the text.

![image](https://github.com/user-attachments/assets/216c9c67-2ff9-4042-a05d-10c707519cb4)

Visible here: https://www.philundrob.de/

**Comment by FoskyM** [comment]
I've checked your website and **didn't** find this problem on my device.
Is it caused by **cache**? Or if it need **specific conditions**?

**Comment by orschiro** [comment]
Hm, you're right.

I just refreshed, and I am no longer seeing this problem either.

Sorry about that!

Probably cache. :)

**Comment by FoskyM** [comment]
> I am no longer seeing this problem either.

Alright, that's fine.
